<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" name="Default test" tests="2" failures="1" timestamp="9 May 2020 18:37:28 GMT" time="109.994" errors="0">
  <testcase name="feature" time="48.876" classname="testrunner.MyTestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [?Product successfully added to your shopping cart] but found [Product successfully added to your shopping cart]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [?Product successfully added to your shopping cart] but found [Product successfully added to your shopping cart]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at testrunner.MyTestRunner.feature(MyTestRunner.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.AssertionError: expected [?Product successfully added to your shopping cart] but found [Product successfully added to your shopping cart]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.prestashop.pageObjects.ItemSearchPage.itemAddedSuccessfully(ItemSearchPage.java:97)
	at com.prestashop.stepDefinitions.TC_003_AddTo_Cart.i_validate_that_item_added_to_the_cart_successfully(TC_003_AddTo_Cart.java:55)
	at ✽.Then I validate that item added to the cart successfully(addToCart.feature:12)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="60.148" classname="testrunner.MyTestRunner"/>
</testsuite> <!-- Default test -->
